version: "2"

volumes:
  db_data:
    driver: local
  gem_data:
    driver: local
  redis_data:
    driver: local

services:
  rails:
    build:
      context: .
    volumes:
      - .:/usr/src/app:cached
      - gem_data:/usr/src/app/vendor/bundle
    environment:
      RAILS_ENV: development
      RDS_HOSTNAME: db
      RDS_USERNAME: root
      RDS_PASSWORD:
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      GITHUB_KEY: $GITHUB_KEY
      GITHUB_SECRET: $GITHUB_SECRET
      MANUAL: $MANUAL

  web:
    extends:
      service: rails
    ports:
      - "3000:3000"
    command: bin/start_dev_server.sh
    depends_on:
      - db
      - redis

  sidekiq:
    extends:
      service: rails
    command: bin/start_dev_sidekiq.sh
    depends_on:
      - db
      - redis

  webpack:
    build:
      context: ./containers/node
    ports:
      - "3333:3333"
    command: bin/start_webpack_server.sh
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      FIREBASE_API_KEY: $FIREBASE_API_KEY
      FIREBASE_AUTH_DOMAIN: $FIREBASE_AUTH_DOMAIN
      FIREBASE_DB_URL: $FIREBASE_DB_URL
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET
      FIREBASE_SENDER_ID: $FIREBASE_SENDER_ID

  db:
    build:
      context: ./containers/db
    ports:
      - "3307:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bestcode_development
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
