default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: reviewhub_development

test:
  <<: *default
  database: reviewhub_test

production:
  <<: *default
  database: reviewhub_production
  username: reviewhub
  password: <%= ENV['REVIEWHUB_DATABASE_PASSWORD'] %>
