default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RDS_HOSTNAME") { "localhost" } %>
  username: <%= ENV.fetch("RDS_USERNAME") { "root" } %>
  password: <%= ENV.fetch("RDS_PASSWORD") { "" } %>

development:
  <<: *default
  database: bestcode_development

test:
  <<: *default
  database: bestcode_test

production:
  <<: *default
  database: bestcode_production
