default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RAILS_DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("RAILS_DB_USER") { "root" } %>
  password: <%= ENV.fetch("RAILS_DB_PASS") { "" } %>

development:
  <<: *default
  database: bestcode_development

test:
  <<: *default
  database: bestcode_test

production:
  <<: *default
  database: bestcode_production
  username: bestcode
  password: <%= ENV['BESTCODE_DATABASE_PASSWORD'] %>
